# Generated by Django 3.1.2 on 2020-10-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onpick', '0002_onpickyoutube'),
    ]

    operations = [
        migrations.AddField(
            model_name='onpickyoutube',
            name='onpick_youtube',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
