# Generated by Django 3.1.2 on 2020-10-19 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onpick', '0004_onpickyoutube_onpick_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='onpickyoutube',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onpick.category'),
        ),
    ]
