# Generated by Django 3.1.2 on 2020-10-19 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trend',
            old_name='trend_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='trend',
            name='ip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.ip'),
        ),
    ]
