# Generated by Django 3.1.2 on 2020-10-21 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_dietcomment_foodcomment_lifecomment_petcomment_stylecomment_trendcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendcomment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trendcomment',
            name='parent',
        ),
    ]
